#!/usr/bin/env node
// Reads Foundry compiled artifacts and emits a typed TS file with the new vault ABI.
// Run automatically after `forge build`. Output is checked into git so the Next.js app
// can build without Foundry installed.

import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(__dirname, "..");

const artifacts = [
  {
    artifact: "contracts/out/HearstVault.sol/HearstVault.json",
    output: "src/config/abi/hearst-vault-v2.ts",
    constName: "HEARST_VAULT_ABI",
  },
  {
    artifact: "contracts/out/HearstPosition.sol/HearstPosition.json",
    output: "src/config/abi/hearst-position.ts",
    constName: "HEARST_POSITION_ABI",
  },
];

const HEADER = `// AUTO-GENERATED by scripts/sync-abi.mjs — DO NOT EDIT.
// Source: Foundry artifacts in contracts/out. Regenerate via \`npm run contracts:build\`.
`;

let updated = 0;
for (const { artifact, output, constName } of artifacts) {
  const artifactPath = resolve(repoRoot, artifact);
  if (!existsSync(artifactPath)) {
    console.error(`[sync-abi] missing artifact: ${artifact}. Did you run \`forge build\`?`);
    process.exitCode = 1;
    continue;
  }
  const json = JSON.parse(readFileSync(artifactPath, "utf8"));
  const abi = json.abi;
  const body = `${HEADER}
export const ${constName} = ${JSON.stringify(abi, null, 2)} as const;
`;
  const outputPath = resolve(repoRoot, output);
  const prev = existsSync(outputPath) ? readFileSync(outputPath, "utf8") : "";
  if (prev !== body) {
    writeFileSync(outputPath, body);
    console.log(`[sync-abi] wrote ${output} (${abi.length} entries)`);
    updated++;
  } else {
    console.log(`[sync-abi] ${output} unchanged`);
  }
}

if (updated > 0) {
  console.log(`[sync-abi] ${updated} file(s) updated.`);
}
